#!/bin/bash

mkdir -p ${DOCKERDATA}/{frab,frab-mariadb}
cp .env ${DOCKERDATA}/frab/.env
docker run --name frab-mariadb -v ${DOCKERDATA}/frab-mariadb:/var/lib/mysql --env-file ./.env -d mariadb:latest
sleep 3
docker logs --timestamps frab-mariadb
TIMESTAMP=$(docker logs --timestamps frab-mariadb 2>&1 | tail -n1 | cut -d ' ' -f 1)
READY=0
while [ $READY -lt 1 ]; do
  sleep 3
  READY=$(docker logs frab-mariadb 2>&1 | grep "ready for connections." | wc -l)
  docker logs --timestamps --since $TIMESTAMP frab-mariadb
  TIMESTAMP=$(docker logs --timestamps frab-mariadb 2>&1 | tail -n1 | cut -d ' ' -f 1)
done

docker run --name frab -e PASSENGER_APP_ENV=production -v ${DOCKERDATA}/frab:/home/frab/public --link frab-mariadb:mysql -p 80:80 -p 25:25 -p 587:587 -p 465:465 -d freme/frab; docker logs --timestamps --follow frab

### backup db
#. ./.env
#docker exec frab-mariadb sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > ${DOCKERDATA}/all-databases.sql
#docker exec frab-mariadb sh -c 'exec mysqldump --databases -uroot -p"$MYSQL_ROOT_PASSWORD" ${MYSQL_DATABASE}' > ${DOCKERDATA}/${MYSQL_DATABASE}.sql


